image: node:alpine

definitions:
  caches:
    npm: ~/.npm

pipelines:
  branches:
    release/staging:
      - step:
          name: Build app
          deployment: test
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - apk add --no-cache git
            - npm ci
            - npx eas-cli build --platform all --profile preview  --non-interactive --no-wait
    release/production:
      - step:
          name: Build app
          deployment: test
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - apk add --no-cache git
            - npm ci
            - npx eas-cli build --platform all --profile production  --non-interactive --no-wait
